### ISSUE TITLE
Not detecting env variable

### ISSUE THREAD

**Issue by gzheng92** [npiv/chatblade#2]
Steps:

I installed via `pip install .`
Added `OPENAI_API_KEY="sk-blahblahblahblah"` in my .env file
Confirmed that `echo $OPENAI_API_KEY` prints the expected result
Ran `chatblade is this working` and got `expecting openai API Key` back
Confirmed that `chatblade is this working --openai-api-key $OPENAI_API_KEY` does work

My setup is zsh, MacOS, python 3.11.2

**Comment by gzheng92** [comment]
Reading through the code, the issue is that the code uses `os.environ` which doesn't work with .env files, even when they are explicitly sourced. I think it would be fixed by using `dotenv.load_dotenv()`

**Comment by npiv** [comment]
I'm a little torn on this.

My understanding of .env is more as a project specific setting, e.g. for a webapp where you might quickly want to swap out env variables for dev/test/prod.

If there is a popular demand for it as an extra way to manage the open ai key I'd consider adding it

**Comment by paulclark** [comment]
> If there is a popular demand for it as an extra way to manage the open ai key I'd consider adding it

Great project. I'd like to see this.

**Comment by beaugunderson** [comment]
this doesn't seem to work even if the environment variable is set in the environment proper, unfortunately

**Comment by gzheng92** [comment]
I got it to work by adding set +x prior to setting. I imagine it would also
work if you used export
