### ISSUE TITLE
How can I send a pdf to gpt4?

### ISSUE THREAD

**Issue by agarrubio** [npiv/chatblade#22]
`cat my.pdf | chatblade 'explain the following pdf'`

produces an error in `sys.stdin.read()` , called from `parser.get_piped_input()`

The error is `UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c`

Is there a way of sending the pdf?

Many thanks!

**Comment by npiv** [comment]
I'm afraid chatgpt just receives text at this point.  Look at the output of `cat my.pdf` and you should see the issue. You can't just send any arbitrary file/content to chatgpt.

Probably the best solution would be to find some pdftotext utility. Then you could do

`pdftotext my.pdf | chatblade ' ... ' 

Best of luck.
