### ISSUE TITLE
argument --chat-gpt=4 does not work

### ISSUE THREAD

**Issue by yotammanor** [npiv/chatblade#28]
I installed through pip about 20 minutes ago, 3.5 (default) works great, but when I try to provide model 4, I get the following error:

```
➜  chatblade -c 4 write a short poem for me
openai error: The model: `gpt-4` does not exist
```

Is this something you're familiar with?
🙏

**Comment by npiv** [comment]
Hi @yotammanor that is an error from openai itself. 

It means you have not been granted access to gpt-4 yet, you need to join the waiting list I'm afraid
