### ISSUE TITLE
chatblade stream mode -s, the rest of response text is omitted if the text is loger than the terminal window

### ISSUE THREAD

**Issue by KnaveM** [npiv/chatblade#44]
<img width="710" alt="image" src="https://user-images.githubusercontent.com/33738071/232326318-df0c3704-0e16-4798-be58-a516652befbe.png">
the rest of the text is omitted and replace by '...'.
shouldn't chatblade continue printing the response? no need to omit the text and there is no way to scroll down to view the rest of the content until the response has finished.

**Comment by npiv** [comment]
fixed in v0.2.3

**Comment by KnaveM** [comment]
THX!!!
