### ISSUE TITLE
It doesn't accept any API key

### ISSUE THREAD

**Issue by applebait** [npiv/chatblade#46]
What am I doing wrong?
chatblade --openai-api-key <key here>
returns:
no query or option given. nothing to do...
if:
chatblade --openai-api-key key <key here>
returns:
openai error: Incorrect API key provided: key. You can find your API key at https://platform.openai.com/account/api-keys.

About setting it up as a ENV VARIABLE, can someone help, please?
I'm on macOS Ventura, M1

TiA

**Comment by npiv** [comment]
@applebait you need to use your own key. for example say it was sk-test123

you could do `chatblade --open-api-key sk-test123 what is 1 + 1` 

or as an env variable you could do

```
export OPENAI_API_KEY=sk-test123
chatblade what is 1+1
```

If you don't have your own key you need to get one from open ai

**Comment by applebait** [comment]
Ok, working. Thank you so much. :)
