### ISSUE TITLE
All previous answers get printed for new chatblade calls with existing session

### ISSUE THREAD

**Issue by fritzrehde** [npiv/chatblade#48]
I'm not sure if this is a bug or I have just specified that I want this functionality somewhere by accident:
I am using 
```
chatblade \
	--session "$SESSION_NAME" \
	--raw \
	--no-format \
	--only \
	"$query"
```
to call chatblade every time I have a new query (instead of using the interactive mode). What I have noticed, is that, every time I ask another question, chatblade prints *all* of the answers to previous questions as well. E.g. if I have asked three questions so far and ask a fourth (all with seperate/new invocations of the above command I use to launch chatblade), then it will output the answers to the last three questions *and* the output to the foruth question. This is quite annoying, I would only like to see the answer to my latest question (I do want it to remember the last questions/answers of the session, hence I specify it manually). 
Thanks for this awesome tool!

**Comment by fritzrehde** [comment]
I also just got the error
```
openai error: This model's maximum context length is 4097 tokens. However, your messages resulted in 4108 tokens. Please reduce the length of the messages.
```
Is this because openai is always sending back all the previous messages? This seems quite limiting, as I can't continue to have a conversation forever, as I will end up with this error anyways at some point.

**Comment by npiv** [comment]
Hi @fritzrehde,

With regards to the 2nd question, that is your choice. If you use sessions then yes it will send everything back to openAI. Thats how the chats work on the website as well. It is the only way the GPT model has a notion of context. The newer model gpt-4 has a larger max context but is also more pricey.

If however you don't care about the context, then don't use the sessions ofc.

The first question I will have a look at, and provide a fix today/tomorrow

**Comment by fritzrehde** [comment]
Does the interactive session work differently to using a session throughout multiple chatblade instances? Is there also a "limit" with the session in the interactive mode?

**Comment by fritzrehde** [comment]
Also, does chatgpt not store the collection on its server somehow? Intuitively, I would have thought we just have to provide the session and a new prompt, and it has all the previous prompts and answers for that session saved. Is this not the case?

**Comment by fritzrehde** [comment]
Actually, this thought just occured to me: Maybe I am getting the openai error because the payload *sent to me* is too large. I had naively assumed that the payload I was sending to the chatgpt (i.e. all the queries and responses of the specified session) would be *sent to the api*. If the former is the case, then just fixing that chatblade doesn't send back *all* previous responses as well might fix this?

**Comment by npiv** [comment]
> Also, does chatgpt not store the collection on its server somehow? Intuitively, I would have thought we just have to provide the session and a new prompt, and it has all the previous prompts and answers for that session saved. Is this not the case?

No. That's now how it works. Every time you send it a message its completely stateless. Thats just the nature of the large language model. So we provide context ourselves.

So if you want to send everything across for context use -S, if not don't.

If you want to check how big your current conversation has gotten, and everything in it, just use -S with -t and no query. It will show you the whole convo, how many tokens, and an estimated cost.

**Comment by npiv** [comment]
With regards to first question I think  `-e` actually does what you want

**Comment by fritzrehde** [comment]
The only information I have on `-e` is:
```
-e, --extract                   extract content from response if possible (either json or code block)
```
I don't see how this help line explains how it fixes the issues I had. And even if you say it does, then maybe you should change this line from the help menu.

**Comment by fritzrehde** [comment]
You're right though, it does fix my issue. I would, however, be curious to understand why it fixes it.

**Comment by fritzrehde** [comment]
Actually, 
```
chatblade \
	--session "$SESSION_NAME" \
	--stream \
	--extract \
	--raw \
	--no-format \
	--only \
	"$query"
```
now has a different, maybe related, bug: Now it shows the response stream, but once the stream is done, the first part of the response is no longer visible.
