### ISSUE TITLE
ERROR: tiktoken 0.3.3 has requirement requests>=2.26.0, but you'll have requests 2.22.0 which is incompatible.

### ISSUE THREAD

**Issue by teamgroove** [npiv/chatblade#49]
I installed it via cloning and the error pops up: ERROR: tiktoken 0.3.3 has requirement requests>=2.26.0, but you'll have requests 2.22.0 which is incompatible.

I managed to fix it locally with:

pip install --upgrade "requests==2.26.0"

But i think it should work out-of-the-box.

---

 ~ pip install 'chatblade @ git+https://github.com/npiv/chatblade'
Collecting chatblade@ git+https://github.com/npiv/chatblade
  Cloning https://github.com/npiv/chatblade to /tmp/pip-install-xlf9ougx/chatblade
  Running command git clone -q https://github.com/npiv/chatblade /tmp/pip-install-xlf9ougx/chatblade
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting openai>=0.27.2
  Downloading openai-0.27.4-py3-none-any.whl (70 kB)
     |████████████████████████████████| 70 kB 2.0 MB/s
Collecting rich
  Downloading rich-13.3.4-py3-none-any.whl (238 kB)
     |████████████████████████████████| 238 kB 4.0 MB/s
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from chatblade@ git+https://github.com/npiv/chatblade) (5.3.1)
Collecting tiktoken
  Downloading tiktoken-0.3.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 12.2 MB/s
Collecting platformdirs
  Downloading platformdirs-3.4.0-py3-none-any.whl (15 kB)
Requirement already satisfied: tqdm in ./.local/lib/python3.8/site-packages (from openai>=0.27.2->chatblade@ git+https://github.com/npiv/chatblade) (4.64.0)
Requirement already satisfied: aiohttp in ./.local/lib/python3.8/site-packages (from openai>=0.27.2->chatblade@ git+https://github.com/npiv/chatblade) (3.8.1)
Requirement already satisfied: requests>=2.20 in /usr/lib/python3/dist-packages (from openai>=0.27.2->chatblade@ git+https://github.com/npiv/chatblade) (2.22.0)
Collecting typing-extensions<5.0,>=4.0.0; python_version < "3.9"
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting markdown-it-py<3.0.0,>=2.2.0
  Downloading markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
     |████████████████████████████████| 84 kB 1.3 MB/s
Collecting pygments<3.0.0,>=2.13.0
  Downloading Pygments-2.15.1-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 8.7 MB/s
Requirement already satisfied: regex>=2022.1.18 in ./.local/lib/python3.8/site-packages (from tiktoken->chatblade@ git+https://github.com/npiv/chatblade) (2022.4.24)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in ./.local/lib/python3.8/site-packages (from aiohttp->openai>=0.27.2->chatblade@ git+https://github.com/npiv/chatblade) (2.0.12)
Requirement already satisfied: yarl<2.0,>=1.0 in ./.local/lib/python3.8/site-packages (from aiohttp->openai>=0.27.2->chatblade@ git+https://github.com/npiv/chatblade) (1.7.2)
Requirement already satisfied: aiosignal>=1.1.2 in ./.local/lib/python3.8/site-packages (from aiohttp->openai>=0.27.2->chatblade@ git+https://github.com/npiv/chatblade) (1.2.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./.local/lib/python3.8/site-packages (from aiohttp->openai>=0.27.2->chatblade@ git+https://github.com/npiv/chatblade) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp->openai>=0.27.2->chatblade@ git+https://github.com/npiv/chatblade) (19.3.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.local/lib/python3.8/site-packages (from aiohttp->openai>=0.27.2->chatblade@ git+https://github.com/npiv/chatblade) (6.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in ./.local/lib/python3.8/site-packages (from aiohttp->openai>=0.27.2->chatblade@ git+https://github.com/npiv/chatblade) (1.3.0)
Collecting mdurl~=0.1
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp->openai>=0.27.2->chatblade@ git+https://github.com/npiv/chatblade) (2.8)
Building wheels for collected packages: chatblade
  Building wheel for chatblade (PEP 517) ... done
  Created wheel for chatblade: filename=chatblade-0.2.3-py3-none-any.whl size=27555 sha256=f24cf5360089bd6536bbf5c31d35d7eb063e552113175b4f90fa0e7d2517814d
  Stored in directory: /tmp/pip-ephem-wheel-cache-7zc882ev/wheels/0f/f6/d1/5ae4fda48f2c65b64809bc54498c6ce0578678f9c52eaa3829
Successfully built chatblade
ERROR: tiktoken 0.3.3 has requirement requests>=2.26.0, but you'll have requests 2.22.0 which is incompatible.
Installing collected packages: openai, typing-extensions, mdurl, markdown-it-py, pygments, rich, tiktoken, platformdirs, chatblade
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.12.0
    Uninstalling Pygments-2.12.0:
      Successfully uninstalled Pygments-2.12.0
Successfully installed chatblade-0.2.3 markdown-it-py-2.2.0 mdurl-0.1.2 openai-0.27.4 platformdirs-3.4.0 pygments-2.15.1 rich-13.3.4 tiktoken-0.3.3 typing-extensions-4.5.0

**Comment by npiv** [comment]
Hi René,

This isn't really due to chatblade, and just the unfortunate nature of python dependencies. If you want to avoid this you have 2 options:

- use the homebrew install
- use python [virtual environments](https://docs.python.org/3/library/venv.html)

If you want to install in the global space you will need to make sure your dependencies line up.
