### ISSUE TITLE
Light theme issue

### ISSUE THREAD

**Issue by ldelossa** [npiv/chatblade#50]
Really loving chatblade, use it all the time. 

Small issue tho, when a light terminal theme is used, code blocks still render out dark, and typically text is dark on light terms

![image](https://user-images.githubusercontent.com/5642902/235688813-725c3c51-ddf3-4129-b501-97a3a66c52b8.png)

The above is an example, should I look to fix this on my end, or is this something chatblade can figure out?

**Comment by npiv** [comment]
I think this is fixable by adding a paramer to pass a theme to the underlying markdown parser ([rich](https://github.com/Textualize/rich)). Will take a look in the coming days

**Comment by npiv** [comment]
Hi @ldelossa 

Latest version v0.3.0  from main or via pip has the change. homebrew is pending.

You can set the theme via --theme or as an env variable CHATBLADE_THEME. The available styles are here: https://pygments.org/styles/

e.g.
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/452020/235962629-5133051c-ad40-4fc1-b8e4-6e68debaa69a.png">

Do note that you will only get full syntax highlighting like in the example if chatgpt provides a type hint for the language being used. You can check this with -r to get the raw response.

e.g.
<img width="741" alt="image" src="https://user-images.githubusercontent.com/452020/235962882-be7ca242-0d4a-40eb-bea2-fcb799cfedc6.png">

In this case you can see that it indicates it is python at the start of the code block. GPT-4 is really good at this, but gpt 3.5 often doesn't do this. You can create a prompt that hints it to do this though if you like which works quite well for me.

**Comment by ldelossa** [comment]
thanks a ton!

**Comment by jasalt** [comment]
Theme functionality works for code snippets, but having an issue with readability of inline variable names that have black background when using a "high contrast" variation of default Konsole "Black on White" theme which ends up using #2a8080 hex colour for the inline variable text that is too dark to show up.

High contrast variation (better for outdoors):
![Screenshot_20230715_072831](https://github.com/npiv/chatblade/assets/2306521/f0b21158-ce57-4572-a698-a21e0afde3bd)

Original Konsole theme:
![Screenshot_20230715_072756](https://github.com/npiv/chatblade/assets/2306521/da0d585d-2549-407d-831a-a4659bc69641)

Maybe fixable by applying the same code snippet theme to inline variable names, or if background wasn't getting darker than the text.

As a temporary fix, overriding this terminal theme color 7 "intense" variation manually with lighter color.
![image](https://github.com/npiv/chatblade/assets/2306521/a1fed5f6-a43a-4194-8b70-60e5bbc87c77)

Using package chatblade 0.3.1, installed using Python 3.11.2 with pipx.

**Comment by jasalt** [comment]
Also, noting that when using streaming mode with `-s` it seems to use different theme during streaming than what is used after completing full request. As this initial theme looks totally fine as is, could it be used after completion too? Does it have use pygments theme that could be used with `--theme` flag? 

https://github.com/npiv/chatblade/assets/2306521/8ad22bc5-dfa9-4d0e-bb4e-3e11d2bcae39
