### ISSUE TITLE
Fish shell support

### ISSUE THREAD

**Issue by swagatata** [npiv/chatblade#53]
I can't run chatblade on fish shell. 

Even after setting the OPENAI_API_KEY environment variable, I get the error

`openai error: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is
stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See
https://platform.openai.com/account/api-keys for details.`

**Comment by tionis** [comment]
This has nothing to do with the fish shell. You might have a typo or forgotten to export the variable.
It should look something like this: `set -x OPENAI_API_KEY <token_here>`

**Comment by h0useofdupree** [comment]
Running fish aswell and have the same error. Although it doesn't work in bash either. Freshly exporting in bash doesn't do anything too. Neither exporting directly, exporting with set -x or set -U change that problem.
