### ISSUE TITLE
Changing model to gpt-4 does not work

### ISSUE THREAD

**Issue by nshern** [npiv/chatblade#57]
I am not able to use the gpt-4 model.

I tried using -c as explained in the documentation as well as using env variable.

**Comment by npiv** [comment]
What error do you get?

**Comment by nshern** [comment]
I do not get an error. I question it what model it is and I states that it is based on gpt-3 and has no knowledge of the existence of gpt-4

**Comment by npiv** [comment]
That's not how it works :)

If you ask it to take a best guess at what year it is it will tell you it is 2022. The model has a cutoff date on data it was trained from. It doesn't know *what* version it is, it bases responses on when it stopped training.

Ask it "when was gpt-4 released" and it will tell you "As of my knowledge up to October 2021, GPT-4 has not been released yet."

I would refer you to read up more on LLMs, and prompt engineering. But you are using gpt-4.

A better way to test is to ask it something complex, and check the types of responses between 3 and 4. There many examples on twitter where gpt-3 is lacking and what gpt-4 does better.

**Comment by npiv** [comment]
See this thread for more info on the matter: https://old.reddit.com/r/ChatGPT/comments/11rki3b/why_is_gpt4_saying_that_it_is_gpt3_anyone_know/
