### ISSUE TITLE
Apostrophe's aren't escaped in input

### ISSUE THREAD

**Issue by x-candy6** [npiv/chatblade#60]
System:
Windows 10
Windows Terminal>Powershell
Steps to reproduce:
Type a prompt with an apostrophe like
`"I'm trying to setup a web server, could you give me the first steps?"
`
The apostrophe in I'm isn't escaped and causes powershell to wait for input for the ending \'

**Comment by plastik-flasche** [comment]
With powershell from the aur it works just fine! And there isn't really anything chatblade can do to "escape" the apostrophe, as the powershell interpreter is handling that before chatblade is even executed.

**Comment by ahernsean** [comment]
This indicates that this isn't a chatblade issue so much as an issue with the shell from which chatblade is launched. I propose this issue be closed.
