### ISSUE TITLE
Knowledge cut off September 2021 for GPT4

### ISSUE THREAD

**Issue by ldelossa** [npiv/chatblade#62]
Hey there. 

Im probably just confused, but when I use chatblade with the gpt4 model, i get a response that the models knowledge cut off is still 2021. 

When I ask it the same question in my official chat gpt iphone app, i get the response, april 2023. 

Is there anything i must do to use the latest model?

**Comment by npiv** [comment]
Hey @ldelossa 

If you want to use the latest model (released 2 days ago) which has a cutoff of april 2023 and is currently in preview.

you can use `c -c gpt-4-1106-preview`

You can alias that to make it easier, I will be bumping chatblade in the next few days to include this model more easily, and the ability to reference images, as well as some other changes from their last release.

best regards

**Comment by ldelossa** [comment]
Thanks a ton Nick.
