### ISSUE TITLE
API key problems problems

### ISSUE THREAD

**Issue by o0nd7ots** [npiv/chatblade#68]
I have the free plan and I wanted to use the app. I have configured the app an am launching it with `--openai-api-key`.

However no matter what I try to do I get the message
```
openai error: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more 
information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 
'param': None, 'code': 'insufficient_quota'}}
```

What can be the problem?

**Comment by Alucard8181** [comment]
Precisely the same experience here... I'am clueless as well. :S

**Comment by npiv** [comment]
`You exceeded your current quota, please check your plan and billing details. For more 
information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.`

This message comes from openai itself, you exceeded your quota.

**Comment by o0nd7ots** [comment]
If I am using a free account is that the expected response?

**Comment by Alucard8181** [comment]
Is there any way to get this working on a free plan?
