### ISSUE TITLE
looks like -c 4 is not working.

### ISSUE THREAD

**Issue by ziqiaojin** [npiv/chatblade#73]
It does set the model name in debug mode but query return results that are not.
 chatblade --debug -i  -c 4                                                                                                                       ✔  1m 9s  
{
│   'cli input': {
│   │   'query': None,
│   │   'params': {
│   │   │   'openai_api_key': 'chipichipichapachapadubidubidabadaba',
│   │   │   'temperature': 0.0,
│   │   │   'interactive': True,
│   │   │   'stream': False,
│   │   │   'tokens': False,
│   │   │   'prompt_file': None,
│   │   │   'extract': False,
│   │   │   'raw': False,
│   │   │   'no_format': False,
│   │   │   'only': False,
│   │   │   'theme': None,
│   │   │   'session': None,
│   │   │   'session_op': None,
│   │   │   'session_rename': None,
│   │   │   'debug': True,
│   │   │   'model': 'gpt-4'
│   │   }
│   }
}
query (type 'quit' to exit): : Are you gpt3 or gpt4 and what is your knowledge cutoff date?  
{'counted': {'md_links': 0, 'md_text': 0, 'md_inline_blocks': 0, 'md_blocks': 0}}
{'detected': 'regular'}
───────────────────────────────────────────────────────────────────────────────────────── assistant ──────────────────────────────────────────────────────────────────────────────────────────
I am an AI model developed by OpenAI and I'm based on GPT-3. My training only includes knowledge up to September 2020, and I don't have the ability to access or retrieve personal data unless
it has been shared with me in the course of our conversation. I am designed to respect user privacy and confidentiality.
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

gpt4 should have knowledge cutoff date of 2023

Same question in web interface: 

Are you gpt3 or gpt4 and what is your knowledge cutoff date?
ChatGPT:
I am based on the GPT-4 architecture, and my knowledge is up to date as of April 2023.

Tried the arch package and pip install with repo.

**Comment by npiv** [comment]
Hi @ziqiaojin 

Asking the model what model it is doesn't work.

see here: https://old.reddit.com/r/ChatGPT/comments/11rki3b/why_is_gpt4_saying_that_it_is_gpt3_anyone_know/

 From the debug what is being sent to openai is 'model': 'gpt-4'

See the different models here: https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
