### ISSUE TITLE
Azure OpenAI support for preview version fix

### ISSUE THREAD

**Issue by thaapaniemi** [npiv/chatblade#76]
The current version of chatblade doesn't work with at least 2023-09-01-preview version of API because the parameters **temperature**, **max_tokens**, **presence_penalty** and **top_p** are required. 

I managed to get it working with quick-and-dirty solution by adding these to chat.py DEFAULT_OPENAI_SETTINGS dict. However, I believe that providing the ability to manually adjust these parameters with CLI arguments or environment variables would be a better solution.

**Comment by npiv** [comment]
I merged https://github.com/npiv/chatblade/pull/67 which fixes some things for azure users.

I don't use it myself so its hard to test, let me know if it works for you now
