### ISSUE TITLE
Feature request: Add OPENAI_API_ENDPOINT and --openai-api-endpoint="http://address:port/v1"

### ISSUE THREAD

**Issue by PieBru** [npiv/chatblade#78]
Now that [ollama](https://github.com/ollama/ollama) and other FOSS tools serve an OpenAI API endpoint, this env/parameter will enable the use of local or self-hosted servers.
Thank you,
Piero

**Comment by ronny332** [comment]
+1 from me side. The normal openai library uses the environment variable OPENAI_BASE_URL as override feature for the base url. But your not using it while instantiating the `openai.OpenAi(api_key=...` call (chat.py, line 112 at the current build) and the openai library itself can't use it either, in the way you create the library object.

**Comment by npiv** [comment]
added as `OPENAI_BASE_URL` in 0.4.0
