### ISSUE TITLE
Feature request: Allow retrying

### ISSUE THREAD

**Issue by nukeop** [npiv/chatblade#8]
The API is wonky and gets stuck sometimes. It would be nice to automatically time out and retry after a configurable number of seconds, or just upon pressing a button.

**Comment by npiv** [comment]
The long wait is annoying, I'm not sure a retry makes sense as AFAIK you paid the API cost already so breaking the connection and trying again each time would just incur costs.

I will be implementing https://github.com/npiv/chatblade/issues/12

which will allow you to see the tokens streaming in with `-s`, that should alleviate the idea that nothing is happening
