### ISSUE TITLE
Is there a way to display the active model?

### ISSUE THREAD

**Issue by PaulLaux** [npiv/chatblade#90]
Thanks for this great project.

It seems that not all models are available to all users.
 I'm getting:
![image](https://github.com/user-attachments/assets/591a275b-af02-4b27-a387-721ce4fa28ca)

So if im asking the `4o` model: `chatblade -s -c 4o -i` I will still get response, even if `4o` is not available for me.

Is there a way to display the actual model being used, for each session/query?

**Comment by npiv** [comment]
Hi @PaulLaux 

Add --debug to see the model that gets sent over the wire (and other stuff). 

Hope that helps

**Comment by PaulLaux** [comment]
That helps, thanks!
