### ISSUE TITLE
Bad formatting in code blocks

### ISSUE THREAD

**Issue by danielj-n** [npiv/chatblade#94]
For some reason some of the formatting in my code blocks is off.

I am using `chatblade -s -i` on gpt-4o however I had similar issues on 3.5 recently too.

Version is chatblade 0.6.2 on archlinux from the package `extra/chatblade`. I'm using bash in the alacritty terminal emulator. 

The most common and easily reproducible one happens whenever I request bash code that uses "--" ie. `give me some examples of linux commands using --`. This returns badly formatted results like this:

<img width="960" alt="image" src="https://github.com/user-attachments/assets/3999d948-129c-4a25-9598-a77069a89d4f">

From looking at the stream text before the formatting it looks like chatgpt formatted it correctly

<img width="960" alt="image" src="https://github.com/user-attachments/assets/bd017ea2-a8ac-4630-8f3b-e6bfd94b021d">
 
Does anyone know why this might be?

**Comment by danielj-n** [comment]
I did some digging and unfortunately I think this might be an issue with the newly added latex formatting feature.  I commented out `msg = format_latex(msg)` in `printer.py` and it seems like that removed the issue.

<img width="960" alt="image" src="https://github.com/user-attachments/assets/8b871677-91ce-4548-9522-04aaf1582f0e">

Would the easiest solution just be to prevent latex formatting in code blocks entirely? I don't see why it ever would need to be in code blocks.

**Comment by danielj-n** [comment]
Wrote a small fix, it seems to work. It is a little messy since it uses string replacements. Let me know how I can improve it.

<img width="960" alt="image" src="https://github.com/user-attachments/assets/64f85782-76d5-4a9b-9ad0-22d8580b2419">

<img width="960" alt="image" src="https://github.com/user-attachments/assets/c154331e-3cb0-44cf-a244-28917f2292c7">

This fix also means latex is no longer formatted in code blocks when chatgpt is writing latex in code blocks. But I think this is actually desirable behavior since it tends to only stick things in codeblocks that are meant to be unformatted.

<img width="960" alt="image" src="https://github.com/user-attachments/assets/abd90b01-cb40-4fea-89b1-5bdab19437d4">

**Comment by npiv** [comment]
fixed in 0.6.3

Thx a lot, if you do see any more issues let me know. As mentioned would consider just making latex step opt in.
